version: '3.7'

services:
  web:
    build: .
    command: gunicorn diagramGuru.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DIAGRAM_GURU_DATABASE_USER}
      - POSTGRES_PASSWORD=${DIAGRAM_GURU_DATABASE_PASSWORD}
      - POSTGRES_DB=${DIAGRAM_GURU_DATABASE_NAME}
    ports:
      - 5432:5432
volumes:
  postgres_data:
  static_volume: