version: '3.7'

services:
  web:
    build: .
    container_name: diagramguru_django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 9292:9292
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: drscratchv3_database
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${DRSCRATCH_DATABASE_NAME}
      #- MYSQL_USER=${DRSCRATCH_DATABASE_USER}
      - MYSQL_ROOT_PASSWORD=${DRSCRATCH_DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: "/etc/init.d/mysql status"
      timeout: 40s
      retries: 10
    volumes:
      - dbdata:/var/run/mysqld