version: '3.7'

services:
  web:
    build: .
    container_name: diagramguru_django
    command: gunicorn diagramGuru.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    container_name: diagramguru_database
    environment:
      - POSTGRES_DB=${DIAGRAMGURU_DATABASE_NAME}
      - POSTGRES_USER=${DIAGRAMGURU_DATABASE_USER}
      - POSTGRES_PASSWORD=${DIAGRAMGURU_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
