# Generated by Django 3.1.6 on 2021-04-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='date',
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='image',
        ),
    ]
