# Generated by Django 3.2.4 on 2022-01-16 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210420_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='diagram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
