# Generated by Django 3.1.6 on 2021-02-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bpmn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_content', models.TextField(max_length=0)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
